import os
import django
import random
import string

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'deliciae_core.settings')
django.setup()

from core.models import User, Restaurant, FoodItem

def generate_random_string(length=10):
    return ''.join(random.choices(string.ascii_letters, k=length))

def populate_massive():
    print("🚀 Starting Massive Data Population...")
    print("This will generate ~1,000 Restaurants and ~100,000 Food Items.")

    # 1. Create Mock Users for Restaurants
    num_restaurants = 1000
    items_per_restaurant = 100
    
    print(f"Creating {num_restaurants} Restaurant Users...")
    users = []
    for i in range(num_restaurants):
        username = f"res_user_{i}_{generate_random_string(5)}"
        users.append(User(username=username, role=User.IS_RESTAURANT))
    
    User.objects.bulk_create(users, ignore_conflicts=True)
    created_users = User.objects.filter(role=User.IS_RESTAURANT).order_by('-id')[:num_restaurants]

    # 2. Create Restaurants
    print("Creating Restaurant Profiles...")
    cuisines = ['Italian', 'Indian', 'Chinese', 'Mexican', 'Japanese', 'American', 'Thai', 'French']
    locations = ['Downtown', 'Uptown', 'Midtown', 'Westside', 'Eastside', 'Suburbs', 'Riverside']
    
    restaurants = []
    base_img = "https://source.unsplash.com/random/500x500/?restaurant"
    
    for i, user in enumerate(created_users):
        name = f"Best Resto {i} {generate_random_string(3)}"
        restaurants.append(Restaurant(
            user=user,
            name=name,
            cuisine_type=random.choice(cuisines),
            location=random.choice(locations),
            rating=round(random.uniform(3.0, 5.0), 1),
            image_url=base_img
        ))
    
    Restaurant.objects.bulk_create(restaurants)
    all_restaurants = Restaurant.objects.all().order_by('-id')[:num_restaurants]

    # 3. Create Food Items (The big part)
    print("Generating 100,000 Food Items (this might take a moment)...")
    
    food_names = ['Burger', 'Pizza', 'Pasta', 'Sushi', 'Salad', 'Tacos', 'Curry', 'Steak', 'Sandwich', 'Soup']
    adjectives = ['Spicy', 'Cheesy', 'Grilled', 'Fresh', 'Crispy', 'Hot', 'Sweet', 'Savory', 'Mega', 'Classic']
    
    food_items = []
    count = 0
    total_target = num_restaurants * items_per_restaurant
    
    for res in all_restaurants:
        for _ in range(items_per_restaurant):
            name = f"{random.choice(adjectives)} {random.choice(food_names)} {generate_random_string(3)}"
            food_items.append(FoodItem(
                restaurant=res,
                name=name,
                description="Delicious food item generated by AI.",
                price=round(random.uniform(5.0, 50.0), 2),
                category=res.cuisine_type,
                trend_score=round(random.uniform(0.0, 10.0), 1),
                is_available=random.choice([True, True, True, False]), # Mostly available
                image_url=f"https://source.unsplash.com/random/500x500/?{random.choice(food_names)}"
            ))
            count += 1
            
            if len(food_items) >= 5000: # Batch insert
                FoodItem.objects.bulk_create(food_items)
                print(f"  Inserted {count} items...")
                food_items = []

    if food_items:
        FoodItem.objects.bulk_create(food_items)
        
    print(f"✅ DONE! Successfully added {num_restaurants} restaurants and {count} food items.")

if __name__ == '__main__':
    populate_massive()
