# Generated by Django 6.0 on 2026-01-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_picture_alter_foodanalytics_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to a short food video', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.CharField(blank=True, help_text="User's current city/area for food recommendations", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodanalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
