# Generated by Django 4.2 on 2026-02-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dining', 'Dining'), ('delivery', 'Delivery')], default='dining', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Preparing', 'Preparing'), ('Served', 'Served'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Paid', 'Paid')], default='Ordered', max_length=20),
        ),
    ]
