# Generated by Django 4.2 on 2026-02-15 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_bill_id_alter_booking_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodanalytics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
