# Generated by Django 4.2 on 2026-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_foodanalytics_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reel',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
