# Generated by Django 4.2 on 2026-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_reel_engagement_score_reel_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reel_images/'),
        ),
        migrations.AddField(
            model_name='reel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='is_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reel',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to the video file', null=True),
        ),
    ]
